create table if not exists products (
  url text primary key,
  name text not null,
  price text,
  category text,
  product_type text,
  brand text,
  updated_at timestamptz not null default now()
);

create table if not exists product_attributes (
  product_url text primary key references products(url) on delete cascade,
  target_species text[] not null default '{}',
  water_type text[] not null default '{}',
  fishing_position text[] not null default '{}',
  technique text[] not null default '{}',
  experience_level text,
  verified_notes text,
  use_case text,
  extra jsonb not null default '{}'::jsonb,
  source_url text,
  source_hash text,
  extraction_method text,
  extraction_confidence double precision,
  evidence jsonb not null default '[]'::jsonb,
  updated_by text,
  updated_at timestamptz not null default now()
);

create table if not exists chat_feedback (
  id uuid primary key default gen_random_uuid(),
  session_id text not null,
  user_message text not null,
  bot_response text not null,
  correction text,
  debug_snapshot jsonb not null default '{}'::jsonb,
  status text not null default 'flagged',
  flagged_by text,
  resolved_by text,
  created_at timestamptz not null default now(),
  resolved_at timestamptz
);

create table if not exists bot_sessions (
  session_id text primary key,
  history jsonb not null default '[]'::jsonb,
  known_context jsonb not null default '{}'::jsonb,
  last_classification jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create table if not exists processed_whatsapp_messages (
  message_id text primary key,
  from_phone text,
  created_at timestamptz not null default now()
);

create table if not exists bot_events (
  id bigint generated by default as identity primary key,
  session_id text not null,
  channel text not null default 'whatsapp',
  user_message text not null,
  bot_response text,
  intent text,
  products jsonb not null default '[]'::jsonb,
  latency_ms integer,
  handoff boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists handoff_requests (
  id bigint generated by default as identity primary key,
  session_id text not null,
  phone text,
  intent text,
  last_message text,
  status text not null default 'open' check (status in ('open','contacted','closed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists bot_sessions_updated_at_idx on bot_sessions(updated_at desc);
create index if not exists processed_whatsapp_messages_created_idx on processed_whatsapp_messages(created_at desc);
create index if not exists bot_events_created_at_idx on bot_events(created_at desc);
create index if not exists bot_events_session_id_idx on bot_events(session_id);
create index if not exists handoff_requests_status_idx on handoff_requests(status, created_at desc);
